# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GroupSigma <- function(iter, N, ngroups, A, B, init, bsqn, m0) {
    .Call('_MultiTrait_GroupSigma', PACKAGE = 'MultiTrait', iter, N, ngroups, A, B, init, bsqn, m0)
}

SampleVariance <- function(idx, BtB, S, R, M, v, tau, iter, init) {
    .Call('_MultiTrait_SampleVariance', PACKAGE = 'MultiTrait', idx, BtB, S, R, M, v, tau, iter, init)
}

