# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SampleVariance <- function(idx, BtB, S, R, M, v, tau, iter, init) {
    .Call('_MultiTrait_SampleVariance', PACKAGE = 'MultiTrait', idx, BtB, S, R, M, v, tau, iter, init)
}

rcppeigen_hello_world <- function() {
    .Call('_MultiTrait_rcppeigen_hello_world', PACKAGE = 'MultiTrait')
}

rcppeigen_outerproduct <- function(x) {
    .Call('_MultiTrait_rcppeigen_outerproduct', PACKAGE = 'MultiTrait', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('_MultiTrait_rcppeigen_innerproduct', PACKAGE = 'MultiTrait', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('_MultiTrait_rcppeigen_bothproducts', PACKAGE = 'MultiTrait', x)
}

